 export const COUNTER_INCREMENT="COUNTER_INCREMENT";
 export const COUNTER_DECREMENT="COUNTER_DECREMENT";
 export const COUNTER_ADD="COUNTER_ADD";
 export const COUNTER_MULTIPLAY="COUNTER_MULTIPLAY";
 export const COUNTER_SUBTRACT="COUNTER_SUBTRACT";
 export const COUNTER_DIVIDE="COUNTER_DIVIDE";